name: show.hacker
markdown: kramdown
url:
github: https://github.com/melvitax/showhacker
exclude: ['node_modules', 'bower_components', 'README.md', 'package.json', 'bower.json']
timezone: 'America/New_York'
fonts:
  - "Lato:400,900,700,500,300,100:latin"
sass:
    style: compressed
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
  envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
