# config.yml

backend:
  name: git-gateway
  branch: master
  repo: melvitax/showhacker.com 
media_folder: 'assets/uploads'
collections:
  - label: "Shows"
    label_singular: Show
    name: "shows"
    folder: "_data/shows"
    format: yml
    create: true
    identifier_field: title
    fields: 
      - {label: Title, name: title, widget: string}
      - {label: Poster, name: poster, widget: image}
      - {label: Description, name: description, widget: string}
      - label: Theater
        name: theater
        widget: relation
        collection: theaters
        searchFields: ["theater"]
        displayFields: ["theater"]
        valueField: "theater"
      - {label: Address, name: address, widget: string}
      - {label: Preview, name: preview, widget: date, format: "YYYY-MM-DD", default: ""}
      - {label: Opening, name: opening, widget: date, format: "YYYY-MM-DD", default: ""}
      - {label: Closing, name: closing, widget: date, format: "YYYY-MM-DD", default: ""}
      - {label: Tony Award, name: tonyaward, widget: boolean}
      - {label: Critic's Pick, name: criticspick, widget: boolean}
      - {label: Trailer, name: trailer, widget: string}
      - {label: Website, name: website, widget: string}
      - label: Tickets
        name: tickets
        widget: list
        fields:
          - {label: Title, name: title, widget: string}
          - label: Type 
            name: type
            widget: "select"
            options: ["access", "digitalLottery", "digitalRush", "linctix", "lottery", "military", "pink", "regular", "rush", "schools", "standing", "student", "studentRush", "thirty", "thirtyUnder35", "thirtyUnder"]
          - {label: URL or Info, name: info, widget: string}
  - label: Theaters
    label_singular: Theater
    name: "theaters"
    folder: "_data/theaters"
    format: yml
    create: true
    identifier_field: theater
    fields:
      - {label: "Theater", name: "theater", widget: string}
      - {label: "Address", name: "address", widget: string}
  - label: Access Tickets
    label_singular: Access Ticket
    name: "accessTickets"
    folder: "_data/accessTickets"
    format: yml
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - label: "Type"
        name: "type"
        widget: "select"
        options: ["rush", "studentRush", "hiptix", "hiptixHigh", "access10", "blueStar"]
      - {label: URL or Info, name: info, widget: string}