# config.yml

backend:
  name: git-gateway
  branch: master
  repo: melvitax/showhacker.com 
media_folder: 'assets/uploads'
publish_mode: editorial_workflow
collections:
  - label: "Global"
    name: "global"
    files:
      - label: "Shows"
        name: "shows"
        file: "_data/broadway/shows.yml"
        fields:
          - label: "Show"
            name: "show"
            widget: list
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Poster, name: poster, widget: image}
              - {label: Description, name: description, widget: string}
              - {label: Theater, name: theater, widget: string}
              - {label: Address, name: address, widget: string}
              - {label: Preview, name: preview, widget: date, format: "YYYY-MM-DD", default: ""}
              - {label: Opening, name: opening, widget: date, format: "YYYY-MM-DD", default: ""}
              - {label: Closing, name: closing, widget: date, format: "YYYY-MM-DD", default: ""}
              - {label: Tony Award, name: tonyaward, widget: boolean}
              - {label: Critic's Pick, name: criticspick, widget: boolean}
              - {label: Trailer, name: trailer, widget: string}
              - {label: Website, name: website, widget: string}
              - label: Tickets
                name: tickets
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - label: Type 
                    name: type
                    widget: list
                    allow_add: false
                    fields: 
                      - {label: Digital Lottery, name: digitalLottery, widget: text}
                      - {label: Lottery, name: lottery, widget: text}
                      - {label: Rush, name: rush, widget: text}
                      - {label: Student Rush, name: studentRush, widget: text}
                      - {label: Digital Rush, name: digitalRush, widget: text}
                      - {label: Standing Room, name: standing, widget: text}
                      - {label: Linctix, name: linctix, widget: text}
                      - {label: Hiptix, name: hiptix, widget: text}
                      - {label: $30 Under, name: thirty, widget: text}
                      - {label: Access, name: access, widget: text}
                      - {label: Regular, name: regular, widget: text}
                  - {label: URL or Info, name: info, widget: string}
              