# config.yml

backend:
  name: git-gateway
  branch: master
  repo: melvitax/showhacker.com 
media_folder: 'assets/uploads'
collections:
  - label: "Broadway"
    name: "broadway"
    files:
      - label: "Shows"
        name: "shows"
        file: "_data/shows.yml"
        fields:
          - label: "Show"
            name: "show"
            widget: list
            fields: 
              - {label: Title, name: title, widget: string}
              - {label: Poster, name: poster, widget: image}
              - {label: Description, name: description, widget: string}
              - {label: Theater, name: theater, widget: string}
              - {label: Address, name: address, widget: string}
              - {label: Preview, name: preview, widget: date, format: "YYYY-MM-DD", default: ""}
              - {label: Opening, name: opening, widget: date, format: "YYYY-MM-DD", default: ""}
              - {label: Closing, name: closing, widget: date, format: "YYYY-MM-DD", default: ""}
              - {label: Tony Award, name: tonyaward, widget: boolean}
              - {label: Critic's Pick, name: criticspick, widget: boolean}
              - {label: Trailer, name: trailer, widget: string}
              - {label: Website, name: website, widget: string}
              - label: Tickets
                name: tickets
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - label: Ticket Type 
                    name: ticket
                    widget: relation
                    collection: broadway
                    entry: tickets
                    searchFields: ["tickets"]
                    displayFields: ["label"]
                    valueField: "name"
                  - {label: URL or Info, name: info, widget: string}
      - label: Tickets
        name: "tickets"
        file: "_data/tickets.yml"
        fields:
          - name: tickets
            label: tickets
            widget: list
            fields:
              - {label: "Label", name: "label", widget: string}
              - {label: "Name", name: "name", widget: string}
                